# Generated by Django 5.1.1 on 2024-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('reporter_location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('validé', 'Validé'), ('invalidé', 'Invalidé')], default='invalidé', max_length=10)),
                ('reporter_phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
