# Generated by Django 5.1.1 on 2024-10-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_suspiciouscase_delete_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspiciouscase',
            old_name='reporter_phone_number',
            new_name='reporter_phone',
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='status',
            field=models.CharField(choices=[('validated', 'Validated'), ('invalidated', 'Invalidated')], default='invalidated', max_length=15),
        ),
    ]
