# Generated by Django 5.1.1 on 2024-10-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_reporter_phone_number_suspiciouscase_reporter_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('status', models.CharField(choices=[('valid', 'Validé'), ('invalid', 'Invalidé')], default='invalid', max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='SuspiciousCase',
        ),
    ]
