# Generated by Django 5.1.1 on 2024-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportedcase_delete_suspiciouscase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('reporter_location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('invalidated', 'Invalidated')], default='invalidated', max_length=15)),
                ('reporter_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='ReportedCase',
        ),
    ]
