# Generated by Django 5.1.1 on 2024-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_suspiciouscase_delete_reportedcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciouscase',
            name='nom_signale',
            field=models.CharField(default='Moluh', max_length=100),
        ),
    ]
