# Generated by Django 5.1.1 on 2024-10-14 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_suspiciouscase_nom_signale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspiciouscase',
            name='nom_signale',
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='status',
            field=models.CharField(choices=[('validé', 'Validé'), ('invalidé', 'Invalidé')], default='invalidé', max_length=10),
        ),
    ]
