# Generated by Django 5.1.1 on 2024-10-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_suspiciouscase_nom_signale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspiciouscase',
            old_name='reporter_location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='suspiciouscase',
            name='status',
            field=models.CharField(choices=[('validated', 'Validated'), ('invalidated', 'Invalidated')], default='invalidated', max_length=12),
        ),
    ]
