# Generated by Django 5.1.1 on 2024-10-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_rename_reporter_location_suspiciouscase_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('symptoms', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('valid', 'Validé'), ('invalid', 'Invalidé')], default='invalid', max_length=10)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='SuspiciousCase',
        ),
    ]
