# Generated by Django 5.1.1 on 2024-10-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_report_delete_suspiciouscase'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='di', max_length=100),
        ),
    ]
