# Generated by Django 5.1.1 on 2024-10-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
